#!/bin/sh                                                                       
##########################################
#7 - make Baza [ii jj megabytes] 

../a_test 7  1 3  100   &>  x1x3.dat  
../a_test 7  1 4  100   &>  x1x4.dat
../a_test 7  1 5  100   &>  x1x5.dat
../a_test 7  1 6  100   &>  x1x6.dat
../a_test 7  1 7  100   &>  x1x7.dat
../a_test 7  1 8  100   &>  x1x8.dat
../a_test 7  1 9  100   &>  x1x9.dat
../a_test 7  1 10 100   &>  x1x10.dat
  
../a_test 7  2 2  100   &>  x2x2.dat
../a_test 7  2 3  100   &>  x2x3.dat
../a_test 7  2 4  100   &>  x2x4.dat
../a_test 7  2 5  100   &>  x2x5.dat
  
../a_test 7  3 3  100   &>  x3x3.dat

##########################################
#/OLD

# a_test 7  1 3  100  2>  D/x1x3.dat    
# a_test 7  1 4  100  2>  D/x1x4.dat
# a_test 7  1 5  100  2>  D/x1x5.dat

##########################################
