#!/bin/sh                                                                       
##########################################
#9 - read Baza [ii jj]

cd .. 

a_test 9  1 3  
a_test 9  1 4
a_test 9  1 5
a_test 9  1 6
a_test 9  1 7
a_test 9  1 8
a_test 9  1 9
a_test 9  1 10

a_test 9  2 2
a_test 9  2 3
a_test 9  2 4
a_test 9  2 5

a_test 9  3 3

echo ""
echo "=================================="

##########################################
